import SwiftUI

struct SettingsView: View {
    @ObservedObject private var config = AppConfig.shared

    var body: some View {
        Form {
            Section {
                LabeledContent("Device ID") {
                    Text(config.deviceID)
                        .foregroundStyle(.secondary)
                        .font(.footnote)
                        .textSelection(.enabled)
                }
            } header: {
                Text("Your Device")
            } footer: {
                Text("Auto-generated. Copy this into AHB_ALLOWED_DEVICES on your Mac.")
            }

            Section {
                TextField("Your name or short ID", text: $config.userID)
                    .autocorrectionDisabled()
                    .textInputAutocapitalization(.never)
            } header: {
                Text("User ID")
            } footer: {
                Text("E.g. alice. Must match AHB_USER_ID on your Mac.")
            }

            Section {
                TextField("my-mac.tail12345.ts.net", text: $config.collectorHost)
                    .autocorrectionDisabled()
                    .textInputAutocapitalization(.never)
                    .keyboardType(.URL)
            } header: {
                Text("Collector Host")
            } footer: {
                Text("Your Mac's Tailscale MagicDNS hostname (or LAN IP). Port 8443 is added automatically.")
            }

            Section {
                SecureField("Paste the token from your Mac", text: $config.ingestToken)
                    .autocorrectionDisabled()
                    .textInputAutocapitalization(.never)
            } header: {
                Text("Auth Token")
            } footer: {
                Text("Generated by setup.sh on your Mac. Must match AHB_INGEST_TOKEN.")
            }

            Section {
                HStack {
                    Image(systemName: config.isConfigured ? "checkmark.circle.fill" : "exclamationmark.triangle.fill")
                        .foregroundStyle(config.isConfigured ? .green : .orange)
                    Text(config.isConfigured ? "Ready to sync" : "Fill in all fields above")
                        .foregroundStyle(config.isConfigured ? .primary : .secondary)
                }
            }
        }
        .navigationTitle("Setup")
        .navigationBarTitleDisplayMode(.inline)
    }
}
