#!/usr/bin/env bash
# setup.sh — First-time setup for Apple Health Bridge collector.
# Run once after cloning: bash scripts/setup.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
DB_DIR="$REPO_ROOT/db"

echo ""
echo "=== Apple Health Bridge — Mac Collector Setup ==="
echo ""

# ── 1. Python check ────────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found. Install Python 3.10+ from python.org and retry."
    exit 1
fi
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "✓ Python $PY_VER found"

# ── 2. Virtual environment ─────────────────────────────────────────────────────
VENV="$REPO_ROOT/.venv"
if [ ! -d "$VENV" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
pip install -q --upgrade pip
pip install -q -r "$REPO_ROOT/requirements.txt"
echo "✓ Dependencies installed"

# ── 3. Collect user details ────────────────────────────────────────────────────
echo ""
echo "─── Your Identity ───────────────────────────────────────────────────────"
read -rp "  Enter a short user ID (e.g. alice, bob): " USER_ID
USER_ID="${USER_ID// /-}"   # replace spaces with dashes
if [ -z "$USER_ID" ]; then
    echo "ERROR: user ID cannot be empty."
    exit 1
fi

echo ""
echo "─── Device Allowlist ────────────────────────────────────────────────────"
echo "  The iOS app shows your Device ID on the Setup screen."
echo "  It looks like:  iphone-a1b2c3d4"
read -rp "  Paste your iPhone Device ID: " DEVICE_ID
DEVICE_ID="${DEVICE_ID// /}"
if [ -z "$DEVICE_ID" ]; then
    echo "ERROR: device ID cannot be empty."
    exit 1
fi

# ── 4. Generate auth token ─────────────────────────────────────────────────────
TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo ""
echo "─── Auth Token (generated) ──────────────────────────────────────────────"
echo "  $TOKEN"
echo "  → Copy this into the Auth Token field in the iOS app Settings."

# ── 5. Write .env ──────────────────────────────────────────────────────────────
mkdir -p "$DB_DIR"
cat > "$ENV_FILE" <<EOF
# Apple Health Bridge — collector environment
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file (it is in .gitignore).

AHB_USER_ID=$USER_ID
AHB_INGEST_TOKEN=$TOKEN
AHB_ALLOWED_DEVICES=$DEVICE_ID
AHB_DB_PATH=$DB_DIR/health.db
EOF
chmod 600 "$ENV_FILE"
echo ""
echo "✓ .env written to $ENV_FILE"

# ── 6. Tailscale instructions ──────────────────────────────────────────────────
echo ""
echo "─── Tailscale (required for anywhere access) ────────────────────────────"
echo "  1. Download Tailscale for Mac: https://tailscale.com/download"
echo "  2. Sign in and enable MagicDNS in the admin console."
echo "  3. Download Tailscale for iOS from the App Store."
echo "  4. Sign in with the SAME Tailscale account on your iPhone."
echo "  5. Find your Mac's MagicDNS hostname in System Tray → Tailscale"
echo "     It looks like: your-macbook.tail12345.ts.net"
echo "  6. Enter that hostname in the iOS app's Collector Host field."
echo ""
echo "─── Start the collector ─────────────────────────────────────────────────"
echo "  Run this command whenever you want to receive health data:"
echo ""
echo "    bash scripts/start.sh"
echo ""
echo "  Or manually:"
echo "    source .venv/bin/activate && source .env && python -m mac.collector.main"
echo ""
echo "─── OpenClaw / Claude Code skill ────────────────────────────────────────"
echo "  Once data is flowing, open Claude Code and run:"
echo ""
echo "    /health-query"
echo ""
echo "  Or query manually:"
echo "    python scripts/query_health.py --user-id $USER_ID"
echo ""
echo "=== Setup complete! ==================================================="
echo ""
