#!/usr/bin/env bash
# setup.sh — First-time setup for Apple Health Bridge collector.
# Run once after cloning: bash scripts/setup.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
DB_DIR="$REPO_ROOT/db"

echo ""
echo "=== Apple Health Bridge — Mac Collector Setup ==="
echo ""

# ── 1. Python check ────────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found. Install Python 3.10+ from python.org and retry."
    exit 1
fi
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "✓ Python $PY_VER found"

# ── 2. Virtual environment ─────────────────────────────────────────────────────
VENV="$REPO_ROOT/.venv"
if [ ! -d "$VENV" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
pip install -q --upgrade pip
pip install -q -r "$REPO_ROOT/requirements.txt"
echo "✓ Dependencies installed"

# ── 3. Collect user details ────────────────────────────────────────────────────
echo ""
echo "─── Your Identity ───────────────────────────────────────────────────────"
read -rp "  Enter a short user ID (e.g. alice, bob): " USER_ID
USER_ID="${USER_ID// /-}"   # replace spaces with dashes
if [ -z "$USER_ID" ]; then
    echo "ERROR: user ID cannot be empty."
    exit 1
fi

echo ""
echo "─── Device Allowlist ────────────────────────────────────────────────────"
echo "  The iOS app shows your Device ID on the Setup screen."
echo "  It looks like:  iphone-a1b2c3d4"
read -rp "  Paste your iPhone Device ID: " DEVICE_ID
DEVICE_ID="${DEVICE_ID// /}"
if [ -z "$DEVICE_ID" ]; then
    echo "ERROR: device ID cannot be empty."
    exit 1
fi

# ── 4. Generate auth token ─────────────────────────────────────────────────────
TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo ""
echo "─── Auth Token (generated) ──────────────────────────────────────────────"
echo "  $TOKEN"
echo "  → Copy this into the Auth Token field in the iOS app Settings."

# ── 5. Write .env ──────────────────────────────────────────────────────────────
mkdir -p "$DB_DIR"
cat > "$ENV_FILE" <<EOF
# Apple Health Bridge — collector environment
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file (it is in .gitignore).

AHB_USER_ID=$USER_ID
AHB_INGEST_TOKEN=$TOKEN
AHB_ALLOWED_DEVICES=$DEVICE_ID
AHB_DB_PATH=$DB_DIR/health.db
EOF
chmod 600 "$ENV_FILE"
echo ""
echo "✓ .env written to $ENV_FILE"

# ── 6. TLS certificate (required for iOS App Transport Security) ───────────────
echo ""
echo "─── HTTPS / TLS (required for iOS) ──────────────────────────────────────"
echo "  iOS blocks all plain HTTP traffic (App Transport Security)."
echo "  The easiest fix: let Tailscale issue a free, trusted certificate."
echo "  This requires MagicDNS to be enabled in your Tailscale admin console."
echo ""
TS_HOSTNAME=""
_TS_BLOCKED=""
if ! command -v tailscale &>/dev/null; then
    _TS_BLOCKED="not installed"
else
    _TS_STATUS_ERR=$(tailscale status 2>&1 >/dev/null || true)
    if echo "$_TS_STATUS_ERR" | grep -qi "not running\|failed to connect\|is tailscale running"; then
        _TS_BLOCKED="not running"
    else
        TS_HOSTNAME=$(tailscale status --self --json 2>/dev/null \
            | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['Self']['DNSName'].rstrip('.'))" \
            2>/dev/null || echo "")
    fi
fi

if [ "$_TS_BLOCKED" = "not installed" ]; then
    echo "  Tailscale is not installed."
    echo "  Download from https://tailscale.com/download, sign in, then re-run setup.sh."
    echo "  Without HTTPS, iOS will block all connections."
elif [ "$_TS_BLOCKED" = "not running" ]; then
    echo "  Tailscale is installed but not running."
    echo "  Start it:  `sudo tailscaled` (or start the Tailscale GUI app, if installed)"
    echo "  Then re-run: bash scripts/setup.sh"
    echo "  Without HTTPS, iOS will block all connections."
elif [ -n "$TS_HOSTNAME" ]; then
    echo "  Detected hostname: $TS_HOSTNAME"
    read -rp "  Issue a free TLS certificate for this hostname now? [Y/n] " SETUP_TLS
    if [[ "${SETUP_TLS:-y}" =~ ^[Yy] ]]; then
        CERT_DIR="$REPO_ROOT/certs"
        mkdir -p "$CERT_DIR"
        _CERT_ERR=$(tailscale cert \
            --cert-file "$CERT_DIR/server.crt" \
            --key-file  "$CERT_DIR/server.key" \
            "$TS_HOSTNAME" 2>&1) && _CERT_OK=true || _CERT_OK=false
        if $_CERT_OK; then
            cat >> "$ENV_FILE" <<ENVEOF

AHB_TLS_CERT=$CERT_DIR/server.crt
AHB_TLS_KEY=$CERT_DIR/server.key
ENVEOF
            echo "✓ TLS certificate written to $CERT_DIR/"
            echo "  The collector will serve HTTPS — iOS connections will work."
        else
            echo ""
            echo "  WARNING: 'tailscale cert' failed."
            if echo "$_CERT_ERR" | grep -qi "does not support\|not support.*tls\|not support.*cert"; then
                echo ""
                echo "  Your Tailscale account has HTTPS certificates disabled."
                echo "  Fix:"
                echo "    1. Go to https://login.tailscale.com/admin/dns"
                echo "    2. Scroll to 'HTTPS Certificates' and click Enable"
                echo "    3. Re-run: bash scripts/setup.sh"
            else
                echo "  $_CERT_ERR"
                echo "  Make sure MagicDNS and HTTPS Certificates are both enabled at"
                echo "  https://login.tailscale.com/admin/dns"
                echo "  then re-run: bash scripts/setup.sh"
            fi
        fi
    else
        echo "  Skipped. Add AHB_TLS_CERT and AHB_TLS_KEY to .env when ready."
        echo "  Without HTTPS, iOS will block all connections."
    fi
else
    echo "  Tailscale is running but no MagicDNS hostname was found."
    echo "  Enable MagicDNS at https://login.tailscale.com/admin/dns"
    echo "  then re-run: bash scripts/setup.sh"
    echo "  Without HTTPS, iOS will block all connections."
fi
echo ""
echo "─── Start the collector ─────────────────────────────────────────────────"
echo "  Run this command whenever you want to receive health data:"
echo ""
echo "    bash scripts/start.sh"
echo ""
echo "  Or manually:"
echo "    source .venv/bin/activate && source .env && python -m mac.collector.main"
echo ""
echo "─── OpenClaw / Claude Code skill ────────────────────────────────────────"
echo "  Once data is flowing, open Claude Code and run:"
echo ""
echo "    /health-query"
echo ""
echo "  Or query manually:"
echo "    python scripts/query_health.py --user-id $USER_ID"
echo ""
echo "=== Setup complete! ==================================================="
echo ""
